// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchOrderRequest) Reset() {
	*x = DispatchOrderRequest{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchOrderRequest) ProtoMessage() {}

func (x *DispatchOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchOrderRequest.ProtoReflect.Descriptor instead.
func (*DispatchOrderRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DispatchOrderRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

type DispatchOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TrackingCode  string                 `protobuf:"bytes,2,opt,name=tracking_code,json=trackingCode,proto3" json:"tracking_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchOrderResponse) Reset() {
	*x = DispatchOrderResponse{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchOrderResponse) ProtoMessage() {}

func (x *DispatchOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchOrderResponse.ProtoReflect.Descriptor instead.
func (*DispatchOrderResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchOrderResponse) GetTrackingCode() string {
	if x != nil {
		return x.TrackingCode
	}
	return ""
}

func (x *DispatchOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\x12\bshipping\"X\n" +
	"\x14DispatchOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\"p\n" +
	"\x15DispatchOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rtracking_code\x18\x02 \x01(\tR\ftrackingCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2c\n" +
	"\x0fShippingService\x12P\n" +
	"\rDispatchOrder\x12\x1e.shipping.DispatchOrderRequest\x1a\x1f.shipping.DispatchOrderResponseB\vZ\tshipping/b\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shipping_proto_goTypes = []any{
	(*DispatchOrderRequest)(nil),  // 0: shipping.DispatchOrderRequest
	(*DispatchOrderResponse)(nil), // 1: shipping.DispatchOrderResponse
}
var file_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.ShippingService.DispatchOrder:input_type -> shipping.DispatchOrderRequest
	1, // 1: shipping.ShippingService.DispatchOrder:output_type -> shipping.DispatchOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}
