version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

## MONITORING
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ADMIN_USER: admin
      GF_AUTH_ADMIN_PASSWORD: password
    volumes:
      - grafana_data:/var/lib/grafana



volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local