---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: grpc
      port: 8007
      targetPort: 8007
    - name: metrics
      port: 8082
      targetPort: 8082
  type: NodePort