---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - name: grpc
      port: 8011
      targetPort: 8011
    - name: metrics
      port: 8082
      targetPort: 8082
  type: NodePort