---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - name: grpc
      port: 8008
      targetPort: 8008
    - name: metrics
      port: 8082
      targetPort: 8082
  type: NodePort