apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: payment-service
  labels:
    release: prometheus-stack    # (OU use o .Release.Name do Helm Stack Prometheus)
spec:
  selector:
    matchLabels:
      app: payment-service
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 10s