apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-servicemonitor
  namespace: monitoring    # geralmente onde está seu Prometheus
  labels:
    release: prometheus    # precisa bater com o label do Prometheus do Helm chart!
spec:
  selector:
    matchLabels:
      app: catalog-service
  namespaceSelector:
    matchNames:
      - default            # namespace onde está sua API Go (pode ser "default")
  endpoints:
    - port: metrics        # Porta conforme declarada no Service!
      path: /metrics
      interval: 10s